### ISSUE TITLE
Android Blog link is dead

### ISSUE THREAD

**Issue by gopar** [fasteque/fasteque.github.io#2]
Did you get rid of the blog?
http://www.fasteque.com/

**Comment by fasteque** [comment]
Yes, I haven't updated the blog or worked on Android for more than one year and few months ago I haven't renewed the domain.
I'll remove the link form the github page.

Did you need something in specific? I might be able to get back some content.

**Comment by gopar** [comment]
Ah alright.
I was able to use web.archive.org to view the original posts I was interested in. 

Thanks though!
